"""
@Time:2021/11/30 11:23
@Author:deanywang
@File:analisy.py
@return:""
"""

aa=[
    {
        "title":"画布 1",
        "topic":{
            "title":"XJL_0930版本",
            "topics":[    #xmind_modleName       self.testResult = self.xmind_modleName[m]['topics'][0]['topics'][0]['topics']     print('获取到的结果为：', self.testResult)
                {
                    "title":"模块1",
                    "topics":[     #xmind_caseNum
                        {
                            "title":"测试用例1",
                            "makers":[
                                "priority-1"
                            ],
                            "topics":[
                                {
                                    "title":"测试步骤1",
                                    "topics":[
                                        {
                                            "title":"测试结果1"
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            "title":"测试用例2",
                            "makers":[
                                "priority-2"
                            ],
                            "topics":[
                                {
                                    "title":"测试步骤2",
                                    "topics":[
                                        {
                                            "title":"测试结果2"
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            "title":"测试用例3",
                            "makers":[
                                "priority-3"
                            ],
                            "topics":[
                                {
                                    "title":"测试步骤3",
                                    "topics":[
                                        {
                                            "title":"测试结果3"
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            "title":"测试用例4",
                            "makers":[
                                "priority-4"
                            ],
                            "topics":[
                                {
                                    "title":"测试结果4"
                                }
                            ]
                        }
                    ]
                },
                {
                    "title":"模块2",
                    "topics":[
                        {
                            "title":"子模块2",
                            "topics":[
                                {
                                    "title":"测试用例5",
                                    "makers":[
                                        "priority-1"
                                    ],
                                    "topics":[
                                        {
                                            "title":"测试步骤5",
                                            "topics":[
                                                {
                                                    "title":"测试结果5"
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    "title":"测试用例6",
                                    "makers":[
                                        "priority-2"
                                    ],
                                    "topics":[
                                        {
                                            "title":"测试结果6"
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            "title":"子模块3",
                            "topics":[
                                {
                                    "title":"测试用例7",
                                    "makers":[
                                        "priority-1"
                                    ],
                                    "topics":[
                                        {
                                            "title":"测试步骤7",
                                            "topics":[
                                                {
                                                    "title":"测试结果7"
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    "title":"测试用例8",
                                    "makers":[
                                        "priority-2"
                                    ],
                                    "topics":[
                                        {
                                            "title":"测试结果8"
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        "structure":"org.xmind.ui.map.unbalanced"
    }
]

